/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedCatalogueRouteImport } from './routes/_authenticated/catalogue'
import { Route as AuthenticatedCirculationRouteImport } from './routes/_authenticated/circulation'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedLoansRouteImport } from './routes/_authenticated/loans'
import { Route as AuthenticatedManageRouteImport } from './routes/_authenticated/manage'
import { Route as AuthenticatedPlatformRouteImport } from './routes/_authenticated/platform'
import { Route as AuthenticatedShelfRouteImport } from './routes/_authenticated/shelf'
import { Route as AuthenticatedBooksBookIdRouteImport } from './routes/_authenticated/books.$bookId'
import { Route as AuthenticatedCatalogueResourceIdRouteImport } from './routes/_authenticated/catalogue.$resourceId'
import { Route as AuthenticatedReadResourceIdRouteImport } from './routes/_authenticated/read.$resourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogueRoute = AuthenticatedCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCirculationRoute =
  AuthenticatedCirculationRouteImport.update({
    id: '/circulation',
    path: '/circulation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLoansRoute = AuthenticatedLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManageRoute = AuthenticatedManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformRoute = AuthenticatedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShelfRoute = AuthenticatedShelfRouteImport.update({
  id: '/shelf',
  path: '/shelf',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksBookIdRoute =
  AuthenticatedBooksBookIdRouteImport.update({
    id: '/books/$bookId',
    path: '/books/$bookId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogueResourceIdRoute =
  AuthenticatedCatalogueResourceIdRouteImport.update({
    id: '/$resourceId',
    path: '/$resourceId',
    getParentRoute: () => AuthenticatedCatalogueRoute,
  } as any)
const AuthenticatedReadResourceIdRoute =
  AuthenticatedReadResourceIdRouteImport.update({
    id: '/read/$resourceId',
    path: '/read/$resourceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/catalogue': typeof AuthenticatedCatalogueRouteWithChildren
  '/circulation': typeof AuthenticatedCirculationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/manage': typeof AuthenticatedManageRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/shelf': typeof AuthenticatedShelfRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/catalogue/$resourceId': typeof AuthenticatedCatalogueResourceIdRoute
  '/read/$resourceId': typeof AuthenticatedReadResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/catalogue': typeof AuthenticatedCatalogueRouteWithChildren
  '/circulation': typeof AuthenticatedCirculationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/loans': typeof AuthenticatedLoansRoute
  '/manage': typeof AuthenticatedManageRoute
  '/platform': typeof AuthenticatedPlatformRoute
  '/shelf': typeof AuthenticatedShelfRoute
  '/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/catalogue/$resourceId': typeof AuthenticatedCatalogueResourceIdRoute
  '/read/$resourceId': typeof AuthenticatedReadResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/catalogue': typeof AuthenticatedCatalogueRouteWithChildren
  '/_authenticated/circulation': typeof AuthenticatedCirculationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/loans': typeof AuthenticatedLoansRoute
  '/_authenticated/manage': typeof AuthenticatedManageRoute
  '/_authenticated/platform': typeof AuthenticatedPlatformRoute
  '/_authenticated/shelf': typeof AuthenticatedShelfRoute
  '/_authenticated/books/$bookId': typeof AuthenticatedBooksBookIdRoute
  '/_authenticated/catalogue/$resourceId': typeof AuthenticatedCatalogueResourceIdRoute
  '/_authenticated/read/$resourceId': typeof AuthenticatedReadResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/catalogue'
    | '/circulation'
    | '/dashboard'
    | '/library'
    | '/loans'
    | '/manage'
    | '/platform'
    | '/shelf'
    | '/books/$bookId'
    | '/catalogue/$resourceId'
    | '/read/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/catalogue'
    | '/circulation'
    | '/dashboard'
    | '/library'
    | '/loans'
    | '/manage'
    | '/platform'
    | '/shelf'
    | '/books/$bookId'
    | '/catalogue/$resourceId'
    | '/read/$resourceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/catalogue'
    | '/_authenticated/circulation'
    | '/_authenticated/dashboard'
    | '/_authenticated/library'
    | '/_authenticated/loans'
    | '/_authenticated/manage'
    | '/_authenticated/platform'
    | '/_authenticated/shelf'
    | '/_authenticated/books/$bookId'
    | '/_authenticated/catalogue/$resourceId'
    | '/_authenticated/read/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogue': {
      id: '/_authenticated/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AuthenticatedCatalogueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/circulation': {
      id: '/_authenticated/circulation'
      path: '/circulation'
      fullPath: '/circulation'
      preLoaderRoute: typeof AuthenticatedCirculationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loans': {
      id: '/_authenticated/loans'
      path: '/loans'
      fullPath: '/loans'
      preLoaderRoute: typeof AuthenticatedLoansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage': {
      id: '/_authenticated/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof AuthenticatedManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform': {
      id: '/_authenticated/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof AuthenticatedPlatformRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shelf': {
      id: '/_authenticated/shelf'
      path: '/shelf'
      fullPath: '/shelf'
      preLoaderRoute: typeof AuthenticatedShelfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$bookId': {
      id: '/_authenticated/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AuthenticatedBooksBookIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogue/$resourceId': {
      id: '/_authenticated/catalogue/$resourceId'
      path: '/$resourceId'
      fullPath: '/catalogue/$resourceId'
      preLoaderRoute: typeof AuthenticatedCatalogueResourceIdRouteImport
      parentRoute: typeof AuthenticatedCatalogueRoute
    }
    '/_authenticated/read/$resourceId': {
      id: '/_authenticated/read/$resourceId'
      path: '/read/$resourceId'
      fullPath: '/read/$resourceId'
      preLoaderRoute: typeof AuthenticatedReadResourceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCatalogueRouteChildren {
  AuthenticatedCatalogueResourceIdRoute: typeof AuthenticatedCatalogueResourceIdRoute
}

const AuthenticatedCatalogueRouteChildren: AuthenticatedCatalogueRouteChildren =
  {
    AuthenticatedCatalogueResourceIdRoute:
      AuthenticatedCatalogueResourceIdRoute,
  }

const AuthenticatedCatalogueRouteWithChildren =
  AuthenticatedCatalogueRoute._addFileChildren(
    AuthenticatedCatalogueRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCatalogueRoute: typeof AuthenticatedCatalogueRouteWithChildren
  AuthenticatedCirculationRoute: typeof AuthenticatedCirculationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedLoansRoute: typeof AuthenticatedLoansRoute
  AuthenticatedManageRoute: typeof AuthenticatedManageRoute
  AuthenticatedPlatformRoute: typeof AuthenticatedPlatformRoute
  AuthenticatedShelfRoute: typeof AuthenticatedShelfRoute
  AuthenticatedBooksBookIdRoute: typeof AuthenticatedBooksBookIdRoute
  AuthenticatedReadResourceIdRoute: typeof AuthenticatedReadResourceIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCatalogueRoute: AuthenticatedCatalogueRouteWithChildren,
  AuthenticatedCirculationRoute: AuthenticatedCirculationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedLoansRoute: AuthenticatedLoansRoute,
  AuthenticatedManageRoute: AuthenticatedManageRoute,
  AuthenticatedPlatformRoute: AuthenticatedPlatformRoute,
  AuthenticatedShelfRoute: AuthenticatedShelfRoute,
  AuthenticatedBooksBookIdRoute: AuthenticatedBooksBookIdRoute,
  AuthenticatedReadResourceIdRoute: AuthenticatedReadResourceIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
